In [9]:
import numpy as np
a=np.zeros((3,3))
print(a)
b=np.ones((3,3))
print(b)
c=np.eye(3)
print(c)
d=np.arange(0,10,2)
print(d)
e=np.linspace(1,3,5)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[1.  1.5 2.  2.5 3. ]


In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:

print(a.shape)
print(a.ndim)
print(a.size)


(3, 3)
2
9


In [12]:
x=np.array([1,2,3])
y=np.array([4,5,6])

print(x+y)
print(x-y)
print(x/y)
print(x//y)
print(x**y)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[0 0 0]
[  1  32 729]


In [13]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[0:])
print(arr[::2])


1
5
[2 3 4]
[1 2 3 4 5]
[1 3 5]


In [14]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr1[0,1])
print(arr1[0:2,1:])
print(arr1[:,0])
print(arr1>25)
print(arr1[[0,2,1]])
print(arr1[arr1<9])


2
[[2 3]
 [5 6]]
[1 4 7]
[[False False False]
 [False False False]
 [False False False]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]
[1 2 3 4 5 6 7 8]


np.linalg.det
np.linalg.
np.linalg.

In [15]:
import pandas as pd


In [16]:
df=pd.read_csv("/content/Students Social Media Addiction.csv")

In [17]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7


In [18]:
df.describe()

,Student_ID,Age,Avg_Daily_Usage_Hours,Sleep_Hours_Per_Night,Mental_Health_Score,Conflicts_Over_Social_Media,Addicted_Score
count,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000
mean,353.000000,20.659574,4.918723,6.868936,6.226950,2.849645,6.436879
std,203.660256,1.399217,1.257395,1.126848,1.105055,0.957968,1.587165
min,1.000000,18.000000,1.500000,3.800000,4.000000,0.000000,2.000000
25%,177.000000,19.000000,4.100000,6.000000,5.000000,2.000000,5.000000
50%,353.000000,21.000000,4.800000,6.900000,6.000000,3.000000,7.000000
75%,529.000000,22.000000,5.800000,7.700000,7.000000,4.000000,8.000000
max,705.000000,24.000000,8.500000,9.600000,9.000000,5.000000,9.000000


In [19]:
df['Mental_Health_Score']

,Mental_Health_Score
0,6
1,8
2,5
3,7
4,6
...,...
700,7
701,4
702,6
703,8


In [20]:
df.loc[0:3]

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4


In [21]:
df.iloc[0:5]

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7


In [22]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7


In [23]:
df1=df[["Age","Gender"]]

In [24]:
df1

,Age,Gender
0,19,Female
1,22,Male
2,20,Female
3,18,Male
4,21,Male
...,...,...
700,20,Female
701,23,Male
702,21,Female
703,24,Male


In [25]:
print(df[df["Age"]>22])

     Student_ID  Age  Gender Academic_Level       Country  \
6             7   23    Male       Graduate       Germany   
16           17   24    Male       Graduate        Sweden   
21           22   23  Female       Graduate   Switzerland   
28           29   24    Male       Graduate      Malaysia   
33           34   23  Female       Graduate        Taiwan   
40           41   24    Male       Graduate  South Africa   
45           46   23  Female       Graduate         Chile   
52           53   24    Male       Graduate       Bolivia   
57           58   23  Female       Graduate       Bahamas   
64           65   23    Male       Graduate      Slovakia   
74           75   23    Male       Graduate       Belarus   
87           88   23  Female       Graduate    San Marino   
94           95   23    Male       Graduate        Bosnia   
101         102   23  Female       Graduate          Iraq   
108         109   23    Male       Graduate     Sri Lanka   
571         572   23    

In [26]:
df.isnull()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,False,False,False,False,False,False,False,False,False,False,False,False,False
701,False,False,False,False,False,False,False,False,False,False,False,False,False
702,False,False,False,False,False,False,False,False,False,False,False,False,False
703,False,False,False,False,False,False,False,False,False,False,False,False,False


In [27]:
df.isnull().sum()

,0
Student_ID,0
Age,0
Gender,0
Academic_Level,0
Country,0
Avg_Daily_Usage_Hours,0
Most_Used_Platform,0
Affects_Academic_Performance,0
Sleep_Hours_Per_Night,0
Mental_Health_Score,0


In [28]:
df.fillna(0)

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,20,Female,Undergraduate,Italy,4.7,TikTok,No,7.2,7,In Relationship,2,5
701,702,23,Male,Graduate,Russia,6.8,Instagram,Yes,5.9,4,Single,5,9
702,703,21,Female,Undergraduate,China,5.6,WeChat,Yes,6.7,6,In Relationship,3,7
703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4


In [29]:
df['Age'].fillna(df["Age"].mean(),inplace=True)

/tmp/ipython-input-2703313926.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df["Age"].mean(),inplace=True)


In [30]:
df.dropna()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,20,Female,Undergraduate,Italy,4.7,TikTok,No,7.2,7,In Relationship,2,5
701,702,23,Male,Graduate,Russia,6.8,Instagram,Yes,5.9,4,Single,5,9
702,703,21,Female,Undergraduate,China,5.6,WeChat,Yes,6.7,6,In Relationship,3,7
703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4


In [31]:
df.duplicated().sum()

np.int64(0)

In [32]:
df.drop_duplicates( inplace=True)

In [33]:
df['Age']=df['Age'].astype(int)

df['Date']=pd.to_datetime(df['Date'])

In [34]:
Q1=df['Age'].quantile(0.25)
Q3=df['Age'].quantile(0.75)